debug: false

spring:
  application:
    name: argo-admin
  profiles:
    active: dev
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql



management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    build:
      enabled: true


mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**.xml


argo:
  password:
    salt: 123456

rw:
  wrapExcept: false