server:
  port: 8087

spring:
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    dbcp2:
      validation-query: SELECT 1
      pool-prepared-statements: true
  sql:
    init:
      mode: EMBEDDED
      schema-locations: classpath:/database/schema-h2.sql
      data-locations: classpath:/database/data-h2.sql

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka