server:
  port: 8087

spring:
  # 数据库配置
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./argo-adm;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    dbcp2:
      validation-query: SELECT 1
      pool-prepared-statements: true
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
        trace: true
  sql:
    init:
      mode: ALWAYS
      schema-locations: classpath:/database/schema-h2.sql
      data-locations: classpath:/database/data-h2.sql


# Argo 权限相关信息
argo:
  password:
    salt: 123456
  auth:
    key: F1XX8W35IV8T7GI0Z0MB749D102QY0S1NJYL62RE7BK6G94SVTD
    iv: Z3M6RQGU5C80KTJ70DZIN2RDYW
    token-duration-minutes: 30
    idle-timeout-minutes: 10