server:
  port: 8087

spring:
  # 数据库配置
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/argo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&rewriteBatchedStatements=true&useSSL=false&socketTimeout=30000&connectTimeout=3000
    username: root
    password: root
    dbcp2:
      validation-query: SELECT 1
      pool-prepared-statements: true
  sql:
    init:
      mode: ALWAYS
      schema-locations: classpath:/database/schema-mysql.sql
      data-locations: classpath:/database/data-mysql.sql


# Argo 权限相关信息
argo:
  password:
    salt: 123456
  auth:
    key: F1XX8W35IV8T7GI0Z0MB749D102QY0S1NJYL62RE7BK6G94SVTD
    iv: Z3M6RQGU5C80KTJ70DZIN2RDYW
    token-duration-minutes: 30
    idle-timeout-minutes: 10