server:
  port: 8087

spring:
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/argo:argo-adm;DB_CLOSE_ON_EXIT=FALSE
    dbcp2:
      validation-query: SELECT 1
      pool-prepared-statements: true
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
        trace: true
  sql:
    init:
      mode: EMBEDDED
      schema-locations: classpath:/database/schema-h2.sql
      data-locations: classpath:/database/data-h2.sql

argo:
  password:
    salt: 123456