#
spring:
  application:
    name: liens
  profiles:
    active: dev
  cache:
    type: CAFFEINE
    caffeine:
      spec: initialCapacity=10240,maximumSize=102400,expireAfterAccess=10m
  servlet:
    multipart:
      max-file-size: 10MB



