debug: false

spring:
  application:
    name: argo-cms
  profiles:
    active: dev

server:
  port: 8090
  servlet:
    session:
      cookie:
        http-only: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    build:
      enabled: true

rw:
  wrapExcept: true