debug: false

spring:
  application:
    name: argo-cms
  profiles:
    active: dev

server:
  port: 8090
  servlet:
    session:
      cookie:
        http-only: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    build:
      enabled: true

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**.xml


pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

rw:
  wrapExcept: true