debug: false

spring:
  application:
    name: argo-cms
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    build:
      enabled: true
