debug: false

spring:
  application:
    name: argo-cms
  profiles:
    active: dev

server:
  port: 1127
  servlet:
    session:
      cookie:
        http-only: false
        secure: false


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    build:
      enabled: true

rw:
  wrapExcept: true